<?php
	/**
	 * Created by PhpStorm.
	 * User: Skye
	 * Date: 31/01/2019
	 * Time: 9:26 PM
	 */

	namespace Skyenet\Http;

	class ResponseCodes {
		PUBLIC CONST HTTP_SWITCHING_PROTOCOLS = 101;

		// Everything OK
		PUBLIC CONST HTTP_OK = 200;
		PUBLIC CONST HTTP_SAVED = 201;
		PUBLIC CONST HTTP_ACCEPTED = 202;
		PUBLIC CONST HTTP_NON_AUTHORITATIVE_INFORMATION = 203;
		PUBLIC CONST HTTP_NO_CONTENT = 204;
		PUBLIC CONST HTTP_RESET_CONTENT = 205;
		PUBLIC CONST HTTP_PARTIAL_CONTENT = 206;

		// Stuff Moved
		PUBLIC CONST HTTP_MULTIPLE_CHOICES = 300;
		PUBLIC CONST HTTP_MOVED_PERMANENTLY = 301;
		PUBLIC CONST HTTP_MOVED_TEMPORARILY = 302;
		PUBLIC CONST HTTP_SEE_OTHER = 303;
		PUBLIC CONST HTTP_NOT_MODIFIED = 304;
		PUBLIC CONST HTTP_USE_PROXY = 305;

		// You fucked up
		PUBLIC CONST HTTP_BAD_REQUEST = 400;
		PUBLIC CONST HTTP_UNAUTHORIZED = 401;
		PUBLIC CONST HTTP_PAYMENT_REQUIRED = 402;
		PUBLIC CONST HTTP_FORBIDDEN = 403;
		PUBLIC CONST HTTP_NOT_FOUND = 404;
		PUBLIC CONST HTTP_METHOD_NOT_ALLOWED = 405;
		PUBLIC CONST HTTP_NOT_ACCEPTABLE = 406;
		PUBLIC CONST HTTP_PROXY_AUTHENTICATION_REQUIRED = 407;
		PUBLIC CONST HTTP_REQUEST_TIMEOUT = 408;
		PUBLIC CONST HTTP_CONFLICT = 408;
		PUBLIC CONST HTTP_GONE = 410;
		PUBLIC CONST HTTP_LENGTH_REQUIRED = 411;
		PUBLIC CONST HTTP_PRECONDITION_FAILED = 412;
		PUBLIC CONST HTTP_REQUEST_ENTITY_TOO_LARGE = 413;
		PUBLIC CONST HTTP_REQUEST_URI_TOO_LARGE = 414;
		PUBLIC CONST HTTP_UNSUPPORTED_MEDIA_TYPE = 415;
		PUBLIC CONST HTTP_REQUESTED_RANGE_NOT_SATISFIABLE = 416;
		PUBLIC CONST HTTP_EXPECTATION_FAILED = 417;
		PUBLIC CONST HTTP_IM_A_TEAPOT = 418;

		// We fucked up
		PUBLIC CONST HTTP_INTERNAL_SERVER_ERROR = 500;
		PUBLIC CONST HTTP_NOT_IMPLEMENTED = 501;
		PUBLIC CONST HTTP_BAD_GATEWAY = 502;
		PUBLIC CONST HTTP_SERVICE_UNAVAILABLE = 503;
		PUBLIC CONST HTTP_GATEWAY_TIMEOUT = 504;
		PUBLIC CONST HTTP_VERSION_NOT_SUPPORTED = 505;
	}