name: PHP Composer

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches: '*'

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_USER: user
          MYSQL_PASSWORD: password
          MYSQL_DATABASE: skyenet-test
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 13306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v2

      - name: Verify MySQL connection from container
        run: |
          mysql --host 127.0.0.1 --port 13306 -uroot -ppassword -e "SHOW DATABASES"

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run test suite
        run: composer run-script test
        env:
          SKYENET_CONFIG_FILE: UnitTests/github_actions.json
